from weakref import finalize

from gimmik import HIPMatMul

from pyfr.backends.base import NotSuitableError
from pyfr.backends.hip.provider import HIPKernel, HIPKernelProvider


class HIPGiMMiKKernels(HIPKernelProvider):
    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-hip', 'gimmik-nkerns', 8)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-hip', 'gimmik-nbench', 5)

        # Kernel cache
        self._mul_kerns = {}

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Fetch the matrix
        arr = a.get()

        # Dimensions
        n = b.ncol
        ldb, ldc = b.leaddim, out.leaddim

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Cache key
        ckey = (a.mid, alpha, beta, aligne)

        # Check the kernel cache
        try:
            kern, mm, kmeta, dt = self._mul_kerns[ckey]
        except KeyError:
            ifac = self.backend.autotune_ifac
            kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}'
            kdata = None
            best_kern = None

            mm = HIPMatMul(alpha*arr, beta=beta, aligne=aligne)
            kgen = mm.kernels(a.dtype, kname=kname,
                              gcn_arch=self.backend.props['gcn_arch_name'],
                              warp_size=self.backend.props['warp_size'])

            # Benchmark the sequence of kernels generated by GiMMiK
            try:
                with self._bench_data(save=[out], rand=[b]):
                    for i in range(self.nkerns):
                        src, meta = kgen.send(kdata)
                        kern = self._build_kernel(kname, src, 'iPiPi')

                        grid = mm.launch_config(meta, n)['grid']
                        params = kern.make_params(grid, meta['block'])
                        params.set_args(n, b, ldb, out, ldc)

                        # Obtain the runtime
                        dt = self._benchmark(
                            lambda stream: kern.exec_async(stream, params),
                            nbench=self.nbench
                        )

                        if best_kern is None or dt < ifac*best_kern[-1]:
                            best_kern = kern, mm, meta, dt

                        kdata = {
                            'runtime': dt,
                            'registers': kern.nreg,
                            'local_mem': kern.local_mem
                        }
            except StopIteration:
                pass

            # GiMMiK declines an operator by offering no kernels for it
            if best_kern is None:
                raise NotSuitableError('Matrix is inappropriate for GiMMiK')

            # Update the cache
            self._mul_kerns[ckey] = kern, mm, kmeta, dt = best_kern
            finalize(a, lambda: self._mul_kerns.pop(ckey))

        # Set the parameters, resolving the geometry for this n
        grid = mm.launch_config(kmeta, n)['grid']
        params = kern.make_params(grid, kmeta['block'])
        params.set_args(n, b, ldb, out, ldc)

        class MulKernel(HIPKernel):
            def add_to_graph(self, graph, deps):
                return graph.graph.add_kernel(params, deps)

            def run(self, stream):
                kern.exec_async(stream, params)

        return MulKernel(mats=[a, b, out], dt=dt)
