from weakref import finalize

from gimmik import MetalMatMul, OPERAND_BUFFER, SIG_ABC, SIG_BC
import numpy as np

from pyfr.backends.base import NotSuitableError
from pyfr.backends.metal.provider import MetalKernel, MetalKernelProvider


class MetalGiMMiKKernels(MetalKernelProvider):
    # Call signatures we are able to marshal arguments for
    sigs = frozenset({SIG_BC, SIG_ABC})

    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of non-zeros, else defer to GiMMiK
        if backend.cfg.hasopt('backend-metal', 'gimmik-max-nnz'):
            self.max_nnz = backend.cfg.getint('backend-metal',
                                              'gimmik-max-nnz')
        else:
            self.max_nnz = None

        # Family of the GPU we are generating kernels for
        self.gpu_family = backend.gpu_family

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-metal', 'gimmik-nkerns', 18)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-metal', 'gimmik-nbench', 40)

        # Kernel cache
        self._mul_kerns = {}

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Fetch the matrix
        arr = a.get()

        # Dimensions
        ldb, ldc = b.leaddim, out.leaddim

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Cache key
        ckey = (a.mid, alpha, beta, aligne, ldb, ldc)

        # Check the kernel cache
        try:
            kern, grid, tgrp, kmeta, bufs, dt = self._mul_kerns[ckey]
        except KeyError:
            ifac = self.backend.autotune_ifac
            kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}'
            best_kern = None
            sdata = None

            mm = MetalMatMul(alpha*arr, beta=beta, aligne=aligne, n=b.ncol,
                             ldb=ldb, ldc=ldc)
            kgen = mm.kernels(a.dtype, kname=kname, sigs=self.sigs,
                              gpu_family=self.gpu_family,
                              max_nnz=self.max_nnz)

            # Benchmark the sequence of kernels generated by GiMMiK
            try:
                with self._bench_data(save=[out], rand=[b]):
                    for i in range(self.nkerns):
                        src, meta = kgen.send(sdata)

                        bufs = self._operand_bufs(mm, meta)
                        if bufs is None:
                            continue

                        grid, tgrp = meta['grid'], meta['threadgroup']
                        kargs = self._kernel_args(meta, bufs, b, out)
                        kern = self._build_kernel(kname, src,
                                                  [np.uintp]*len(kargs))

                        # Obtain the runtime
                        dt = self._benchmark(
                            lambda cbuf: kern(cbuf, grid, tgrp, *kargs),
                            nbench=self.nbench
                        )

                        if best_kern is None or dt < ifac*best_kern[-1]:
                            best_kern = kern, grid, tgrp, meta, bufs, dt

                        sdata = {'runtime': dt}
            except StopIteration:
                pass

            # GiMMiK declines an operator by offering no kernels for it
            if best_kern is None:
                raise NotSuitableError('Matrix is inappropriate for GiMMiK')

            # Update the cache
            self._mul_kerns[ckey] = best_kern
            kern, grid, tgrp, kmeta, bufs, dt = best_kern
            finalize(a, lambda: self._mul_kerns.pop(ckey))

        # Set the parameters, rebinding the operands to these matrices
        kargs = self._kernel_args(kmeta, bufs, b, out)

        class MulKernel(MetalKernel):
            def run(self, cbuf):
                kern(cbuf, grid, tgrp, *kargs)

        return MulKernel(mats=[a, b, out], dt=dt)

    def _operand_bufs(self, mm, meta):
        # Buffers for the operands GiMMiK asks us to prepare, else None
        bufs = {}

        for name, spec in meta['operands'].items():
            if name != 'a' or spec['kind'] != OPERAND_BUFFER:
                return None

            buf = self.backend.mem_alloc(spec['nbytes'])
            view = buf.contents().as_buffer(spec['nbytes'])
            np.frombuffer(view, dtype=spec['dtype'])[:] = mm.pack_a(meta)

            bufs[name] = (buf, 0)

        return bufs

    @staticmethod
    def _kernel_args(meta, bufs, b, out):
        mats = {'b': b.data, 'c': out.data} | bufs

        return [mats[name] for name in meta['args']]
