from weakref import finalize

from gimmik import CUDAMatMul, PTXMatMul
import numpy as np

from pyfr.backends.base import NotSuitableError
from pyfr.backends.cuda.provider import CUDAKernel, CUDAKernelProvider


class CUDAGiMMiKKernels(CUDAKernelProvider):
    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-cuda', 'gimmik-nkerns', 8)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-cuda', 'gimmik-nbench', 5)

        # Trim the lower 32 bits of fp64 A constants
        self.f64trim = backend.cfg.getbool('backend-cuda', 'gimmik-trim-fp64',
                                           False)

        # Kernel cache
        self._mul_kerns = {}

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Dimensions
        ldb, ldc = b.leaddim, out.leaddim

        # Cache key
        ckey = (a.mid, alpha, beta, aligne, ldb, ldc)

        try:
            kern, grid, block, dt, dshared, tm = self._mul_kerns[ckey]
        except KeyError:
            # Fetch the matrix, premultiply, and optionally trim
            arr = alpha*a.get()
            if a.dtype == np.float64 and self.f64trim:
                arr = self._trim_f64_low32(arr)

            cc = self.backend.cuda.compute_capability()
            if PTXMatMul.is_suitable(arr, cc):
                self._mul_kerns[ckey] = self._ptx_mul(arr, b, out, beta)
            else:
                self._mul_kerns[ckey] = self._cuda_mul(arr, b, out, beta)
            finalize(a, lambda: self._mul_kerns.pop(ckey))

            kern, grid, block, dt, dshared, tm = self._mul_kerns[ckey]

        # Set the parameters
        params = kern.make_params(grid, block, dshared)

        # Set the input args using tensormaps if needed
        if tm['b_tile'] is not None:
            b_arg = b.tensormap(tm['b_tile'])
        else:
            b_arg = b

        if tm['out_tile'] is not None:
            out_arg = out.tensormap(tm['out_tile'])
        else:
            out_arg = out

        params.set_args(b_arg, out_arg)

        class MulKernel(CUDAKernel):
            def add_to_graph(self, graph, deps):
                return graph.graph.add_kernel(params, deps)

            def run(self, stream):
                kern.exec_async(stream, params)

        return MulKernel(mats=[a, b, out], dt=dt)

    def _cuda_mul(self, arr, b, out, beta):
        # Count number of non-zeros
        nnz, nuq = np.count_nonzero(arr), len(np.unique(np.abs(arr)))

        # Check that A is suitable
        if nuq > 28 and nnz / arr.size > 0.15:
            raise NotSuitableError('Matrix is inappropriate for GiMMiK')

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        ifac = self.backend.autotune_ifac
        kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}'
        kdata = None
        best_kern = None

        # Save a copy of the contents of the output matrix
        out_np = getattr(out, 'parent', out).get()

        # Get the CUDA kernel generator
        mm = CUDAMatMul(arr, beta=beta, aligne=aligne, n=b.ncol,
                        ldb=b.leaddim, ldc=out.leaddim)
        kgen = mm.kernels(
            arr.dtype, kname=kname,
            compute_capability=self.backend.cuda.compute_capability()
        )

        # Benchmark the sequence of kernels generated by GiMMiK
        try:
            for i in range(self.nkerns):
                src, meta = kgen.send(kdata)
                kern = self._build_kernel(kname, src, 'PP')

                # If the kernel is spilling then request more L1
                if kern.local_mem and not kern.shared_mem:
                    kern.set_shared_size(carveout=0)

                # Set the parameters
                params = kern.make_params(meta['grid'], meta['block'])
                params.set_args(b, out)

                # Obtain the runtime
                dt = self._benchmark(
                    lambda stream: kern.exec_async(stream, params),
                    nbench=self.nbench
                )

                if best_kern is None or dt < ifac*best_kern[-1]:
                    best_kern = kern, meta['grid'], meta['block'], dt, 0, None

                kdata = {
                    'runtime': dt,
                    'registers': kern.nreg,
                    'local_mem': kern.local_mem,
                    'shared_mem': kern.shared_mem
                }
        except StopIteration:
            pass

        # Restore the output matrix
        getattr(out, 'parent', out).set(out_np)

        return best_kern

    def _ptx_mul(self, arr, b, out, beta):
        cc = self.backend.cuda.compute_capability()

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        ifac = self.backend.autotune_ifac
        kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}'
        kdata = None
        best_kern = None

        # Save a copy of the contents of the output matrix
        out_np = getattr(out, 'parent', out).get()

        # Get the PTX kernel generator
        mm = PTXMatMul(arr, beta=beta, aligne=aligne, n=b.ncol,
                       ldb=b.leaddim, ldc=out.leaddim)
        kgen = mm.kernels(arr.dtype, kname=kname, compute_capability=cc)

        # Benchmark the sequence of kernels generated by GiMMiK
        try:
            for i in range(self.nkerns):
                src, meta = kgen.send(kdata)
                kern = self._build_kernel(kname, src, 'PP')

                # If the kernel is spilling then request more L1
                if kern.local_mem and not kern.shared_mem:
                    kern.set_shared_size(carveout=0)

                # If the kernel needs more than 48 KiB of shared memory
                sharedb = meta.get('dynamic_shared', 0)
                if sharedb > 48 * 1024:
                    kern.set_shared_size(dynm_shared=sharedb)


                # Set the parameters
                params = kern.make_params(meta['grid'], meta['block'],
                                          sharedb)

                # Setup input args using tensor maps if required
                tm = {'b_tile': meta.get('ws_b_tile'),
                      'out_tile': meta.get('ws_out_tile')}
                b_arg = (b.tensormap(tm['b_tile'])
                         if tm['b_tile'] is not None else b)
                out_arg = (out.tensormap(tm['out_tile'])
                           if tm['out_tile'] is not None else out)
                params.set_args(b_arg, out_arg)

                # Obtain the runtime
                dt = self._benchmark(
                    lambda stream: kern.exec_async(stream, params),
                    nbench=self.nbench
                )

                if best_kern is None or dt < ifac*best_kern[3]:
                    best_kern = (kern, meta['grid'], meta['block'], dt,
                                 sharedb, tm)

                kdata = {
                    'runtime': dt,
                    'registers': kern.nreg,
                    'local_mem': kern.local_mem,
                    'shared_mem': kern.shared_mem
                }
        except StopIteration:
            pass

        # Restore the output matrix
        getattr(out, 'parent', out).set(out_np)

        return best_kern

    @staticmethod
    def _trim_f64_low32(x):
        a = np.ascontiguousarray(np.asarray(x, dtype=np.float64)).copy()
        a.view(np.uint64)[...] &= np.uint64(0xFFFFFFFF00000000)
        return a
