import os
from weakref import finalize

from gimmik import CUDAMatMul, PTXMatMul
import numpy as np

from pyfr.backends.base import NotSuitableError
from pyfr.backends.cuda.provider import CUDAKernel, CUDAKernelProvider


class CUDAGiMMiKKernels(CUDAKernelProvider):
    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-cuda', 'gimmik-nkerns', 8)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-cuda', 'gimmik-nbench', 5)

        # Kernel cache
        self._mul_kerns = {}

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Fetch the matrix and tally up the number of non-zeros
        arr = a.get()
        nnz, nuq = np.count_nonzero(arr), len(np.unique(np.abs(arr)))

        # Check that A is suitable
        if nuq > 28 and nnz / arr.size > 0.15:
            raise NotSuitableError('Matrix is inappropriate for GiMMiK')

        # Dimensions
        ldb, ldc = b.leaddim, out.leaddim

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Cache key
        ckey = (a.mid, alpha, beta, aligne, ldb, ldc)

        # Check the kernel cache
        try:
            kern, grid, block, dt = self._mul_kerns[ckey]
        except KeyError:
            ifac = self.backend.autotune_ifac
            kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}'
            kdata = None
            best_kern = None

            # Save a copy of the contents of the output matrix
            out_np = getattr(out, 'parent', out).get()

            mm = CUDAMatMul(alpha*arr, beta=beta, aligne=aligne, n=b.ncol,
                            ldb=ldb, ldc=ldc)
            kgen = mm.kernels(
                a.dtype, kname=kname,
                compute_capability=self.backend.cuda.compute_capability()
            )

            # Benchmark the sequence of kernels generated by GiMMiK
            try:
                for i in range(self.nkerns):
                    src, meta = kgen.send(kdata)
                    kern = self._build_kernel(kname, src, 'PP')

                    # If the kernel is spilling then request more L1
                    if kern.local_mem and not kern.shared_mem:
                        kern.set_shared_size(carveout=0)

                    # Set the parameters
                    params = kern.make_params(meta['grid'], meta['block'])
                    params.set_args(b, out)

                    # Obtain the runtime
                    dt = self._benchmark(
                        lambda stream: kern.exec_async(stream, params),
                        nbench=self.nbench
                    )

                    if best_kern is None or dt < ifac*best_kern[-1]:
                        best_kern = kern, meta['grid'], meta['block'], dt

                    kdata = {
                        'runtime': dt,
                        'registers': kern.nreg,
                        'local_mem': kern.local_mem,
                        'shared_mem': kern.shared_mem
                    }
            except StopIteration:
                pass

            # Restore the output matrix
            getattr(out, 'parent', out).set(out_np)

            # Update the cache
            self._mul_kerns[ckey] = kern, grid, block, dt = best_kern
            finalize(a, lambda: self._mul_kerns.pop(ckey))

        # Set the parameters
        params = kern.make_params(grid, block)
        params.set_args(b, out)

        class MulKernel(CUDAKernel):
            def add_to_graph(self, graph, deps):
                return graph.graph.add_kernel(params, deps)

            def run(self, stream):
                kern.exec_async(stream, params)

        return MulKernel(mats=[a, b, out], dt=dt)


class PTXGiMMiKKernels(CUDAKernelProvider):
    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-cuda', 'gimmik-ptx-nkerns',
                                         32)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-cuda', 'gimmik-ptx-nbench',
                                         10)

        # Trim the lower 32 bits of fp64 A constants
        self.f64trim = backend.cfg.getbool('backend-cuda', 'gimmik-trim-fp64',
                                           False)

        # Kernel cache
        self._mul_kerns = {}

    @staticmethod
    def _trim_f64_low32(x):
        a = np.ascontiguousarray(np.asarray(x, dtype=np.float64)).copy()
        a.view(np.uint64)[...] &= np.uint64(0xFFFFFFFF00000000)
        return a

    def _set_ws_tensormaps(self, kern, kname, b, out, ws_info):
        n_per_cta, k_pad, m_pad = ws_info
        b_desc = kern.module.get_global(f'{kname}_bdesc')
        c_desc = kern.module.get_global(f'{kname}_cdesc')
        self.backend.cuda.set_tensormap(b_desc[0], b, (n_per_cta, k_pad))
        self.backend.cuda.set_tensormap(c_desc[0], out, (n_per_cta, m_pad))

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Fetch the matrix (optionally trimmed)
        if a.dtype == np.float64 and self.f64trim:
            arr = self._trim_f64_low32(a.get())
        else:
            arr = a.get()

        # Check that A is suitable for sparse or dense templates
        cc = self.backend.cuda.compute_capability()
        if not PTXMatMul.is_suitable(arr, a.dtype, cc):
            raise NotSuitableError('Matrix is inappropriate for GiMMiK')

        # Dimensions
        ldb, ldc = b.leaddim, out.leaddim

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Cache key
        ckey = (a.mid, alpha, beta, aligne, ldb, ldc)

        # Check the kernel cache
        try:
            kern, grid, block, dt, kname, ws_info, sharedb = self._mul_kerns[ckey]
        except KeyError:
            ifac = self.backend.autotune_ifac
            kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}'
            kdata = None
            best_kern = None
            best_ws_info = None

            # Save a copy of the contents of the output matrix
            out_np = getattr(out, 'parent', out).get()

            mm = PTXMatMul(alpha*arr, beta=beta, aligne=aligne, n=b.ncol,
                           ldb=ldb, ldc=ldc)
            kgen = mm.kernels(a.dtype, kname=kname, compute_capability=cc)

            # Benchmark the sequence of kernels generated by GiMMiK
            try:
                for i in range(self.nkerns):
                    src, meta = kgen.send(kdata)
                    kern = self._build_kernel(kname, src, 'PP')

                    # If the kernel is spilling then request more L1
                    if kern.local_mem and not kern.shared_mem:
                        kern.set_shared_size(carveout=0)

                    # If the kernel needs more than 48 KiB of shared memory
                    sharedb = meta.get('dynamic_shared', 0)
                    if sharedb > 48 * 1024:
                        kern.set_shared_size(dynm_shared=sharedb)

                    # Warp-spec template: populate B & C tensor maps in .const
                    if meta.get('ws_tensor_map'):
                        k_pad = ((arr.shape[1] + 3) // 4) * 4
                        ws_info = (meta['ws_n_per_cta'], k_pad,
                                   meta['ws_m_pad'])
                        self._set_ws_tensormaps(kern, kname, b, out, ws_info)
                    else:
                        ws_info = None

                    # Set the parameters
                    params = kern.make_params(meta['grid'], meta['block'],
                                              sharedb)
                    params.set_args(b, out)

                    # Obtain the runtime
                    dt = self._benchmark(
                        lambda stream: kern.exec_async(stream, params),
                        nbench=self.nbench
                    )

                    if best_kern is None or dt < ifac*best_kern[3]:
                        best_kern = (kern, meta['grid'], meta['block'], dt,
                                     sharedb)
                        best_ws_info = ws_info

                    kdata = {
                        'runtime': dt,
                        'registers': kern.nreg,
                        'local_mem': kern.local_mem,
                        'shared_mem': kern.shared_mem
                    }
            except StopIteration:
                pass

            # Restore the output matrix
            getattr(out, 'parent', out).set(out_np)

            if best_kern is None:
                raise NotSuitableError('GiMMiK produced no viable kernels')

            kern, grid, block, dt, sharedb = best_kern
            ws_info = best_ws_info
            self._mul_kerns[ckey] = (kern, grid, block, dt, kname, ws_info,
                                     sharedb)
            finalize(a, lambda: self._mul_kerns.pop(ckey))

        # Re-bind tensor maps in case build- and run-time pointers differ
        if ws_info is not None:
            self._set_ws_tensormaps(kern, kname, b, out, ws_info)

        # Set the parameters (sharedb is per-launch dynamic shared mem)
        params = kern.make_params(grid, block, sharedb)
        params.set_args(b, out)

        class MulKernel(CUDAKernel):
            def add_to_graph(self, graph, deps):
                return graph.graph.add_kernel(params, deps)

            def run(self, stream):
                kern.exec_async(stream, params)

        return MulKernel(mats=[a, b, out], dt=dt)
