from weakref import finalize

from gimmik import CUDAMatMul, PTXMatMul
import numpy as np

from pyfr.backends.base import NotSuitableError
from pyfr.backends.cuda.provider import CUDAKernel, CUDAKernelProvider


class CUDAGiMMiKKernels(CUDAKernelProvider):
    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-cuda', 'gimmik-nkerns', 8)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-cuda', 'gimmik-nbench', 5)

        # Trim the lower 32 bits of fp64 A constants
        self.f64trim = backend.cfg.getbool('backend-cuda', 'gimmik-trim-fp64',
                                           False)

        # Kernel cache
        self._mul_kerns = {}

        # GPU Properties used in generator
        self.cc = self.backend.cuda.compute_capability()
        self.smem_info = self.backend.cuda.smem_info()

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Dimensions
        ldb, ldc = b.leaddim, out.leaddim

        # Cache key
        ckey = (a.mid, alpha, beta, aligne, ldb, ldc)

        try:
            kern, grid, block, dshared, tm, dt = self._mul_kerns[ckey]
        except KeyError:
            # Fetch the matrix, premultiply, and optionally trim
            arr = alpha*a.get()
            if a.dtype == np.float64 and self.f64trim:
                arr = self._trim_f64_low32(arr)

            # Alignment
            if 'align' in b.tags and 'align' in out.tags:
                aligne = self.backend.alignb // b.itemsize
            else:
                aligne = None

            # Pick MM generator
            if PTXMatMul.is_suitable(arr, self.cc):
                kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}_ptx'
                MMClass = PTXMatMul
            elif CUDAMatMul.is_suitable(arr):
                kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}_cuda'
                MMClass = CUDAMatMul
            else:
                raise NotSuitableError('Matrix is inappropriate for GiMMiK')

            # Save a copy of the contents of the output matrix
            out_np = getattr(out, 'parent', out).get()

            # Generate and pick best kernel
            mm = MMClass(arr, beta=beta, aligne=aligne, n=b.ncol, ldb=b.leaddim,
                         ldc=out.leaddim)
            kgen = mm.kernels(arr.dtype, kname=kname,
                              compute_capability=self.cc,
                              smem_info=self.smem_info)
            self._mul_kerns[ckey] = self._mul(kname, kgen, arr.dtype, b, out)
            finalize(a, lambda: self._mul_kerns.pop(ckey))

            kern, grid, block, dshared, tm, dt = self._mul_kerns[ckey]

            # Restore the output matrix
            getattr(out, 'parent', out).set(out_np)

        # Set the parameters
        params = kern.make_params(grid, block, dshared)

        # Set the input args using tensormaps if needed
        #params.set_args((b, tm['b_tile'], {'l2_promotion': 1}), (out,
        #        tm['out_tile'], {'l2_promotion': 1}))
        params.set_args((b, tm['b_tile']), (out, tm['out_tile']))

        class MulKernel(CUDAKernel):
            def add_to_graph(self, graph, deps):
                return graph.graph.add_kernel(params, deps)

            def run(self, stream):
                kern.exec_async(stream, params)

        return MulKernel(mats=[a, b, out], dt=dt)

    def _mul(self, kname, kgen, dtype, b, out):
        static_max = self.smem_info[0]
        ifac = self.backend.autotune_ifac
        kdata = None
        best_kern = None

        # Benchmark the sequence of kernels generated by GiMMiK
        try:
            for i in range(self.nkerns):
                src, meta = kgen.send(kdata)
                kern = self._build_kernel(kname, src, 'PP')

                # If the kernel is spilling then request more L1
                if kern.local_mem and not kern.shared_mem:
                    kern.set_shared_size(carveout=0)

                # If the kernel needs more than static max of shared memory
                sharedb = meta.get('dynamic_shared', 0)
                if sharedb > static_max:
                    kern.set_shared_size(dynm_shared=sharedb)

                # Set the parameters
                params = kern.make_params(meta['grid'], meta['block'],
                                          sharedb)

                # Setup input args using tensor maps if required
                tm = {'b_tile': meta.get('ws_b_tile'),
                      'out_tile': meta.get('ws_out_tile')}
                #params.set_args((b, tm['b_tile'], {'l2_promotion': 1}), (out,
                #tm['out_tile'], {'l2_promotion': 1}))
                params.set_args((b, tm['b_tile']), (out, tm['out_tile']))

                # Obtain the runtime
                dt = self._benchmark(
                    lambda stream: kern.exec_async(stream, params),
                    nbench=self.nbench
                )

                if best_kern is None or dt < ifac*best_kern[-1]:
                    best_kern = (kern, meta['grid'], meta['block'], sharedb,
                                 tm, dt)

                kdata = {
                    'runtime': dt,
                    'registers': kern.nreg,
                    'local_mem': kern.local_mem,
                    'shared_mem': kern.shared_mem
                }
        except StopIteration:
            pass
        return best_kern

    @staticmethod
    def _trim_f64_low32(x):
        a = np.ascontiguousarray(np.asarray(x, dtype=np.float64)).copy()
        a.view(np.uint64)[...] &= np.uint64(0xFFFFFFFF00000000)
        return a
